// src/app/layout.tsx or wherever your RootLayout is defined
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "../context/ThemeContext/Theme.provider";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from "@/components/BootstrapClient";
import dynamic from "next/dynamic";

const ReduxProvider = dynamic(() => import("@/redux/ReduxProvider"), {
  ssr: false
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeContextProvider>{children}</ThemeContextProvider>
        </ReduxProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
